version: '3.8'

services:
  classifier_agent:
    build:
      context: .  
      dockerfile: Dockerfile
    image: text_classifier_agent_tf 
    container_name: tc_agent_runner

    volumes:
      - ./generated_classifiers:/app/generated_classifiers  
    env_file:
      - .env 

    tty: true      
    stdin_open: true 

    command: ["tail", "-f", "/dev/null"] 